# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'WorkletsExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
  )

  target 'WorkletsExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # RN 0.85's prebuilt ReactNativeDependencies pod ships folly headers without
    # folly/coro, but clang enables C++20 coroutines, so Expected.h tries to
    # include the missing folly/coro/Coroutine.h. Disable folly coroutines.
    def add_no_coroutines(config)
      defs = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      defs = defs.split(' ') if defs.is_a?(String)
      defs << 'FOLLY_CFG_NO_COROUTINES=1' unless defs.include?('FOLLY_CFG_NO_COROUTINES=1')
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = defs
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each { |config| add_no_coroutines(config) }
    end
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each { |config| add_no_coroutines(config) }
      end
      aggregate_target.user_project.save
    end
  end
end
